on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable WebSSH for debug'
        default: false
        type: boolean

name: build_and_upload_android_test

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup uv 
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.0"
          python-version: "3.13.2"
          activate-environment: "true"
          github-token: ${{ github.token }}
          enable-cache: "auto"
          restore-cache: "true"
          save-cache: "true"
          prune-cache: "true"
          cache-python: "true"
          add-problem-matchers: "true"
          cache-dependency-glob: |
                **/*requirements*.txt
                **/*requirements*.in
                **/*constraints*.txt
                **/*constraints*.in
                **/pyproject.toml
                **/uv.lock
                **/*.py.lock

      - name: Enable WebSSH Debug
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: fawazahmed0/action-debug@v2
        with:
          credentials: ${{ secrets.ANDROID_TEST_DEBUG_CREDENTIALS }}

      - name: Enable KVM
        run: |
          sudo apt update
          sudo apt install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo adduser $USER kvm
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
        
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-31

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          disable-spellchecker: true
          force-avd-creation: false
          emulator-options: -no-metrics -no-window -gpu swiftshader -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            ${{ secrets.ANDROID_TEST_CONFIG_INIT_SCRIPT }}

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          disable-spellchecker: true
          force-avd-creation: false
          emulator-options: -no-metrics -no-snapshot-save -no-window -gpu swiftshader -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            ${{ secrets.ANDROID_TEST_CONFIG_EXTRACT_SCRIPT }}

          
